version: "3.8"

services:
  kafka:
    image: confluentinc/cp-kafka:7.3.0
    container_name: kafka
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      # KRaft settings
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"

      # Listeners
      KAFKA_LISTENERS: "PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093"
      # Replace ${EC2_PUBLIC_IP} with your EC2 instance's public IP or DNS
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://${EC2_PUBLIC_IP}:9092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"

      # Storage
      KAFKA_LOG_DIRS: "/var/lib/kafka/data"
      CLUSTER_ID: "kraft-cluster-01"

      # Additional settings for stability
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    volumes:
      - kafka-data:/var/lib/kafka/data
      - ./kafka-init.sh:/kafka-init.sh
    entrypoint:
      [
        "/bin/sh",
        "-c",
        "export KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://$(curl -s http://169.254.169.254/latest/meta-data/public-ipv4):9092 && /etc/confluent/docker/run & sleep 20 && sh /kafka-init.sh && wait",
      ]

volumes:
  kafka-data:
